source 'https://rubygems.org'
ruby "3.3.1"

gem "sinatra", "~> 4.0"

gem "sinatra-contrib", "~> 4.0"

gem "sinatra-flash", "~> 0.3.0"

gem "sequel", "~> 5.83"

gem "rackup", "~> 2.1"

gem "haml", "~> 6.3"

gem "puma", "~> 6.4"

gem "activesupport", "~> 7.2"

gem "bcrypt", "~> 3.1"

gem "jwt", "~> 2.8"

gem "dotenv", "~> 3.1"

gem "toml-rb", "~> 3.0"

gem "foreman", "~> 0.88.1"

gem "sqlite3", "~> 2.0"

gem "ffi", "~> 1.17"
